SELECT [id] ,[LabourID] ,[name],[dateOfBirth],[dateOfJoining],[projectName],[companyName]
 ,[SalaryBu],[WorkingBu],[gender],[designationId],[designation] ,[departmentId],[departmentName],[department]
,[address],[pincode],[state],[labourCategoryId] ,[labourCategory] 
,[status],[Reject_Reason] ,[workingHours],[labourOwnership]
,[IsApproved],[Marital_Status]
,[retirementDate]    
      FROM [LabourOnboardingForm].[dbo].[labourOnboarding]



SELECT [Id]
      ,[EmployeeId]
      ,[PunchDate]
      ,[InTime]
      ,[OutTime]
      ,[ShiftId]
      ,[TotalHours]
      ,[IsPresent]
      ,[AttnStatus_1]
      ,[AttnStatus_2] 
      ,[IsMissPunch]
      ,[IsNoPunch]
      ,[IsDataRectified]
  FROM [JDPROJECT].[Payroll].[BiometricAttendance]



= Table.FromRows(Json.Document(Binary.Decompress(Binary.
FromText("i45WciwoysxR0lEyVIrViVbyTawEso3AbK/SvFQgxxjKyQHJmIA5jqXppcUlQK4pmBucWlCSmpuUWgQUMQOL+CeX5EP45mC+X34ZTIEFWMAlNRkmYAkxPzGvNLEIZIWhAVjALTWpCCYCc1tRcgaIC3ReLAA=", 
BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Month = _t, #"Seq." = _t])
